/**
 * Seed curriculum — swap or load from API later.
 * correctLane: 0 = left, 1 = center, 2 = right (matches in-game lanes)
 */
export const QUESTION_POOL = [
  {
    id: "py-print-1",
    topic: "python",
    prompt: "What does print(type([])) show in Python 3?",
    choices: ["<class 'list'>", "<class 'array'>", "<type 'list'>"],
    correctLane: 0,
  },
  {
    id: "py-mut-1",
    topic: "python",
    prompt: "Which is mutable?",
    choices: ["tuple", "list", "str"],
    correctLane: 1,
  },
  {
    id: "js-eq-1",
    topic: "javascript",
    prompt: "What is [] == [] in JavaScript?",
    choices: ["true", "false", "undefined"],
    correctLane: 1,
  },
  {
    id: "js-type-1",
    topic: "javascript",
    prompt: "typeof null in JavaScript is:",
    choices: ["'null'", "'object'", "'undefined'"],
    correctLane: 1,
  },
  {
    id: "git-1",
    topic: "git",
    prompt: "First time linking a local repo to GitHub, you usually:",
    choices: ["git clone", "git remote add origin <url>", "git fork"],
    correctLane: 1,
  },
  {
    id: "big-o-1",
    topic: "algorithms",
    prompt: "Binary search on a sorted array of n items is:",
    choices: ["O(n)", "O(log n)", "O(n log n)"],
    correctLane: 1,
  },
  {
    id: "http-1",
    topic: "web",
    prompt: "Which status means 'Created' after POST?",
    choices: ["200", "201", "204"],
    correctLane: 1,
  },
  {
    id: "sql-1",
    topic: "sql",
    prompt: "Which clause filters rows before grouping?",
    choices: ["HAVING", "WHERE", "ORDER BY"],
    correctLane: 1,
  },
  {
    id: "py-slice-1",
    topic: "python",
    prompt: "In Python 3, what is [1,2,3][::-1]?",
    choices: ["[3,2,1]", "[1,2,3]", "Error"],
    correctLane: 0,
  },
  {
    id: "py-none-1",
    topic: "python",
    prompt: "Which keyword represents “no value” in Python?",
    choices: ["nil", "None", "null"],
    correctLane: 1,
  },
  {
    id: "js-strict-1",
    topic: "javascript",
    prompt: "[] === [] in JavaScript is:",
    choices: ["true", "false", "TypeError"],
    correctLane: 1,
  },
  {
    id: "js-event-1",
    topic: "javascript",
    prompt: "To listen for a click on a DOM node, you typically use:",
    choices: ["addEventListener('click', …)", "onClick = …", "listen('click')"],
    correctLane: 0,
  },
  {
    id: "git-branch-1",
    topic: "git",
    prompt: "Create and switch to a new branch in one step:",
    choices: ["git branch new", "git checkout -b new", "git new branch"],
    correctLane: 1,
  },
  {
    id: "git-stage-1",
    topic: "git",
    prompt: "Stage all changes in the current directory:",
    choices: ["git add .", "git commit -a", "git push"],
    correctLane: 0,
  },
  {
    id: "big-o-2",
    topic: "algorithms",
    prompt: "Inserting at the end of a dynamic array (amortized) is often:",
    choices: ["O(1)", "O(n)", "O(log n)"],
    correctLane: 0,
  },
  {
    id: "http-2",
    topic: "web",
    prompt: "Which method is usually idempotent and safe?",
    choices: ["POST", "GET", "PATCH"],
    correctLane: 1,
  },
  {
    id: "sql-2",
    topic: "sql",
    prompt: "JOIN that keeps all rows from the left table:",
    choices: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN"],
    correctLane: 1,
  },
  {
    id: "math-order-1",
    topic: "math",
    prompt: "What is 2 + 3 × 4 (order of operations)?",
    choices: ["20", "14", "24"],
    correctLane: 1,
  },
  {
    id: "math-sqrt-1",
    topic: "math",
    prompt: "√81 equals:",
    choices: ["9", "8", "7"],
    correctLane: 0,
  },
  {
    id: "math-deriv-1",
    topic: "math",
    prompt: "Derivative of x³ with respect to x is:",
    choices: ["3x²", "x²", "3x"],
    correctLane: 0,
  },
  {
    id: "math-prime-1",
    topic: "math",
    prompt: "Which is a prime number?",
    choices: ["91", "97", "100"],
    correctLane: 1,
  },
  {
    id: "math-log-1",
    topic: "math",
    prompt: "log₁₀(1000) equals:",
    choices: ["2", "3", "10"],
    correctLane: 1,
  },
  {
    id: "math-tri-1",
    topic: "math",
    prompt: "Interior angles of a Euclidean triangle sum to:",
    choices: ["90°", "180°", "360°"],
    correctLane: 1,
  },
  {
    id: "math-geo-1",
    topic: "math",
    prompt: "Area of a circle with radius r is:",
    choices: ["2πr", "πr²", "πd"],
    correctLane: 1,
  },
  {
    id: "asm-mov-1",
    topic: "assembly",
    prompt: "Which mnemonic usually copies bits between operands (x86-style)?",
    choices: ["MOV", "JMP", "RET"],
    correctLane: 0,
  },
  {
    id: "asm-endian-1",
    topic: "assembly",
    prompt: "On common little-endian CPUs, the least significant byte of a word is stored at:",
    choices: ["the highest address", "the lowest address", "a separate cache line only"],
    correctLane: 1,
  },
  {
    id: "asm-immediate-1",
    topic: "assembly",
    prompt: "A constant encoded inside the instruction itself is often called an:",
    choices: ["immediate", "segment", "descriptor table"],
    correctLane: 0,
  },
  {
    id: "asm-call-1",
    topic: "assembly",
    prompt: "A `call` instruction typically pushes so you can return later:",
    choices: ["return address", "all registers", "nothing"],
    correctLane: 0,
  },
  {
    id: "asm-assembler-1",
    topic: "assembly",
    prompt: "An assembler’s main job is to turn assembly into:",
    choices: ["JavaScript", "machine code", "SQL"],
    correctLane: 1,
  },
  {
    id: "asm-stack-1",
    topic: "assembly",
    prompt: "On classic x86, the stack usually grows toward:",
    choices: ["higher addresses", "lower addresses", "fixed ROM"],
    correctLane: 1,
  },
  {
    id: "sci-light-1",
    topic: "science",
    prompt: "Speed of light in vacuum is about:",
    choices: ["3×10⁶ m/s", "3×10⁸ m/s", "3×10¹⁰ m/s"],
    correctLane: 1,
  },
  {
    id: "sci-water-1",
    topic: "science",
    prompt: "Chemical formula for water:",
    choices: ["HO₂", "H₂O", "OH₂"],
    correctLane: 1,
  },
  {
    id: "sci-newton-1",
    topic: "science",
    prompt: "If mass doubles and net force stays the same (F = ma), acceleration:",
    choices: ["doubles", "halves", "stays the same"],
    correctLane: 1,
  },
  {
    id: "sci-alkali-1",
    topic: "science",
    prompt: "Which is an alkali metal often used in batteries?",
    choices: ["Helium", "Lithium", "Argon"],
    correctLane: 1,
  },
];
